<a href="https://colab.research.google.com/github/bindyamannem/fwt/blob/main/numpydemo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
a1=np.array([1,2,3,4])
print(a1)
print(type (a1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
import numpy as np
a1=np.array([1,2,3,4])
print(a1)
print(type (a1))
a2=np.array([5,6,7,8])
print(a2)
print(type(a2))

[1 2 3 4]
<class 'numpy.ndarray'>
[5 6 7 8]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
print(np.array([1,2,3]))

[1 2 3]


In [8]:
import numpy as np
print(np.array((4,5,6)))

[4 5 6]


In [9]:
import numpy as np
print(np.array([[1,2],[3,4]]))

[[1 2]
 [3 4]]


In [10]:
import numpy as np
print(np.arange(0,10,2))

[0 2 4 6 8]


In [11]:
import numpy as np
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [12]:
import numpy as np
print(np.logspace(1,3,3))

[  10.  100. 1000.]


In [13]:
import numpy as np
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [14]:
import numpy as np
print(np.ones((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
import numpy as np
print(np.full(2,2),7)

[2 2] 7


In [16]:
import numpy as np
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
import numpy as np
print(np.identity(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [18]:
import numpy as np
print(np.random.rand(2,3))

[[0.02746763 0.06200927 0.96610584]
 [0.66624898 0.44320547 0.18027115]]


In [19]:
import numpy as np
print(np.random.randn(2,3))

[[-0.74363427 -1.02075117  1.31258468]
 [ 0.47914419 -1.20353686 -0.03192367]]


In [21]:
import numpy as np
print(np.random.randint(1,(2,3)))

[1 2]


In [29]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.size)
print(a.dtype)

(2, 3)
6
int64


In [33]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8])
arr=np.array([10,20,30])
print(np.sort(x),x.sort())
print(np.copy(arr))

[1 2 3 4 5 6 7 8] None
[10 20 30]


In [34]:
import numpy as np
a=20
b=30
print(a+b)

50


In [36]:
import numpy as np
a=20
b=30
print(a+b,a*b)

50 600
